name: UI Web Tests Manual Run
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose Repo Branch:'
        required: true
        default: 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '17'
    - name: Build & Install
      run: mvn --file BDO_Web_Automation/pom.xml -B install -D skipTests --no-transfer-progress
    - name: Install Playwright
      run: mvn --file BDO_Web_Automation/pom.xml exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
    - name: Run tests
      run: mvn --file BDO_Web_Automation/pom.xml -Dtest=MyTest -DargLine="-Dplaywright.browsers=chromium" -e -Dheadless=false
    - name: List the current directory
      run: ls -a
    - name: Check the target folder
      run: cd target
           ls -a
      
